spring.application.name=pomodoro
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=pomodoro

api.security.device-key=${DEVICE_API_KEY:pomodoro-pico-w-secret-key-2025}
api.security.frontend-key=${FRONTEND_API_KEY:pomodoro-frontend-secret-key-2025}

api.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

server.port=${PORT:8080}